(function(){'use strict';
const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const today=new Date(); today.setMinutes(today.getMinutes()-today.getTimezoneOffset());
const date=$('input[name="date"]'); if(date) date.min=today.toISOString().slice(0,10);
const header=$('.site-header'); const toggle=$('#menu-toggle'),nav=$('#main-nav,.main-nav');
function closeMenu(){if(nav)nav.classList.remove('open');document.body.classList.remove('menu-open');if(header)header.classList.remove('menu-is-open');if(toggle)toggle.setAttribute('aria-expanded','false')}
if(toggle)toggle.addEventListener('click',()=>{const open=nav&&!nav.classList.contains('open');if(nav)nav.classList.toggle('open',open);document.body.classList.toggle('menu-open',open);header&&header.classList.toggle('menu-is-open',open);toggle.setAttribute('aria-expanded',String(open))});
$$('.main-nav a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});document.addEventListener('click',e=>{if(nav&&nav.classList.contains('open')&&!e.target.closest('.site-header'))closeMenu()});
function scrollState(){header&&header.classList.toggle('scrolled',scrollY>18);const top=$('#back-to-top');top&&top.classList.toggle('visible',scrollY>500)}addEventListener('scroll',scrollState,{passive:true});scrollState();
const sections=$$('main section[id]'),links=$$('.main-nav a'); if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}}),{rootMargin:'-35% 0px -55%'});sections.forEach(s=>io.observe(s))}
if('IntersectionObserver'in window){document.documentElement.classList.add('js-reveal');const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(x=>io.observe(x))}else $$('.reveal').forEach(x=>x.classList.add('is-visible'));
function msg(el,text,type){if(!el)return;el.textContent=text;el.className='form-message '+(type||'')}
const search=$('#search-form,.trip-form'),searchMsg=$('#search-message,.form-message');if(search)search.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(search),where=String(f.get('destination')||'').trim();if(!where){msg(searchMsg,'Tell us where you would like to go.','error');search.querySelector('[name="destination"]')?.focus();return}if(date&&!date.value){msg(searchMsg,'Choose your travel date.','error');return}msg(searchMsg,'Great choice — explore the matching journeys below.','success');$('#destinations')?.scrollIntoView({behavior:'smooth'});const input=$('#destination-search');if(input){input.value=where;input.dispatchEvent(new Event('input'))}});
function filterCards(buttons,cards,empty){let active='all',query='';function apply(){let count=0;cards.forEach(c=>{const region=(c.dataset.region||'').toLowerCase(),name=(c.dataset.name||c.textContent).toLowerCase(),show=(active==='all'||region===active)&&(!query||name.includes(query));c.hidden=!show;if(show)count++});if(empty)empty.hidden=!!count}buttons.forEach(b=>b.addEventListener('click',()=>{active=(b.dataset.region||'all').toLowerCase();buttons.forEach(x=>x.setAttribute('aria-pressed',String(x===b)));apply()}));return {apply,setQuery:q=>{query=q.toLowerCase();apply()}}}
const destCards=$$('.destination-card'),destButtons=$$('#destination-filters button');if(destCards.length&&destButtons.length){const f=filterCards(destButtons,destCards,$('#destination-empty'));$('#destination-search')?.addEventListener('input',e=>f.setQuery(e.target.value.trim()));$('#clear-search')?.addEventListener('click',()=>{$('#destination-search').value='';f.setQuery('')})}
$$('#package-filters button').forEach(b=>b.addEventListener('click',()=>{const v=(b.dataset.category||'all').toLowerCase();$$('.package-card').forEach(c=>c.hidden=!(v==='all'||(c.dataset.category||'').toLowerCase()===v));$$('#package-filters button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))}));
function prefill(destination,kind){const f=$('#contact-form');if(!f)return;const d=f.querySelector('[name="destination"]');const m=f.querySelector('[name="message"]');if(d&&destination)d.value=destination;if(m&&!m.value)m.value='I would like to enquire about '+(kind||'a journey')+(destination?' in '+destination:'')+'.';$('#contact')?.scrollIntoView({behavior:'smooth'});setTimeout(()=>d?.focus(),500)}
$$('.explore-button').forEach(b=>b.addEventListener('click',()=>prefill(b.dataset.destination,'an experience')));$$('.book-button').forEach(b=>b.addEventListener('click',()=>prefill(b.dataset.destination,b.dataset.package)));
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}const nf=$('#newsletter-form');if(nf)nf.addEventListener('submit',e=>{e.preventDefault();const i=nf.querySelector('input[type=email],input[name=email]'),out=$('#newsletter-message,.newsletter-message');if(!i||!validEmail(i.value.trim())){if(out)out.textContent='Please enter a valid email address.';i?.focus();return}if(out)out.textContent="You're subscribed! Get ready for your next adventure.";nf.reset()});
const cf=$('#contact-form');if(cf)cf.addEventListener('submit',e=>{e.preventDefault();let ok=true;$$('input,textarea,select',cf).forEach(x=>{if(x.required&&!String(x.value).trim()){x.setCustomValidity('Please complete this field.');ok=false}else x.setCustomValidity('')});const email=cf.querySelector('[name=email]');if(email&&email.value.trim()&&!validEmail(email.value.trim())){email.setCustomValidity('Enter a valid email address.');ok=false}if(!cf.checkValidity()){cf.reportValidity();return}if(!ok)return;const out=$('#contact-message,.form-status');if(out)out.textContent='Thanks — your enquiry is saved locally in this page only; nothing was sent.';cf.reset()});
const dialog=$('#info-dialog');$$('[data-info]').forEach(b=>b.addEventListener('click',()=>{const data={guide:['Travel guide','Thoughtful routes, practical notes, and local context to help you travel with intention.'],careers:['Careers','We are not currently publishing open opportunities. Check back for future updates.'],privacy:['Privacy','This demo keeps enquiries in this page only. Fonts and images may be loaded from third-party services.']};const x=data[b.dataset.info]||['Information','More details coming soon.'];$('#dialog-title').textContent=x[0];$('#dialog-body').textContent=x[1];dialog?.showModal() }));$('#dialog-close')?.addEventListener('click',()=>dialog.close());
$('#back-to-top')?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
$$('img').forEach(img=>img.addEventListener('error',()=>{if(img.dataset.failed)return;img.dataset.failed='1';img.src='data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="900" height="600" viewBox="0 0 900 600"%3E%3Crect width="900" height="600" fill="%230f2b35"/%3E%3Cpath d="M0 500L250 280l130 100 150-180L900 500v100H0z" fill="%231b4650"/%3E%3C/svg%3E'}));
$$('.stat-number').forEach(el=>{const target=Number(el.dataset.target);if(!target)return;const suffix=el.dataset.suffix||'';const decimals=Number(el.dataset.decimals||0);el.textContent=(decimals?target.toFixed(decimals):'0')+suffix;const run=()=>{const start=performance.now();const tick=t=>{const p=Math.min(1,(t-start)/1100),v=target*p;el.textContent=(decimals?v.toFixed(decimals):Math.round(v))+suffix;if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)};if(matchMedia('(prefers-reduced-motion: reduce)').matches)el.textContent=target.toFixed(decimals)+suffix;else if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>{if(es[0].isIntersecting){run();io.disconnect()}});io.observe(el)}else run()});
})();
